copado.onpremise.deployment:
  copadoUsername: developer+dev05user1@copa.do
  copadoUrl: https://login.salesforce.com/services/Soap/u/43.0
  copadoPassword: suey-damsel-tibia3467
  copadoToken: oeWRGIwKMiBw8cywJyIcIh20F

  gitUrl: https://github.com/DavidMarquez-Copado/tests.git
  gitUsername: DavidMarquez-Copado
  gitPassword: 5081703840fbb10af104a607fd810b3f47b686c5

  secret: __SUPER_SECRET__

  renameNamespace:

  ## Just for testing with default example services
  00D1t000000otHB:
    url: https://login.salesforce.com/services/Soap/u/43.0
    username: dmarquez@copa.do-dmd.test
    token: 3jhSK0IAWaE1VPbaT7z94bBy
    password: 1234567890A

debug: false # Enable debug logs.
trace: false # Enable trace logs.